### ISSUE TITLE
Error: UNIVERSAL does not export anything at lib/Bio/Tree/TreeFunctionsI.pm line 94

### ISSUE THREAD

**Issue by paulotokimatu** [fgvieira/badirate#1]
I am trying to use BadiRate 1.35, but I am having some problems to run it in my machine. 

When I run `perl BadiRate.pl` I get the following error:
```
UNIVERSAL does not export anything at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl/5.22/base.pm line 97.
	...propagated at /usr/share/perl/5.22/base.pm line 106.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO.pm line 90.
Compilation failed in require at BadiRate.pl line 71.
BEGIN failed--compilation aborted at BadiRate.pl line 71.
One or more DATA sections were not processed by Inline.
```

The root of the problem seems to be that my perl version is 5.22.1. Searching about the issue I found some links that are probably related to the problem:

http://perldoc.perl.org/UNIVERSAL.html#EXPORTS
https://stackoverflow.com/questions/35258993/perl-universal-does-not-export-anything

I am not a perl expert, so in a naive way, if I just comment the line 94 of TreeFunctionsI.pm, it looks like it I can run the script, but I think it is likely that something will break.

**Comment by fgvieira** [comment]
Hi Paulo,

yes, Badirate needs perl <= v5.16. We'll try to fix it but, in the meantime, can you try running Badirate with perl <= v5.16?
You can try perlbrew to install older perl versions.

**Comment by paulotokimatu** [comment]
Thanks for the answer. If there is anything I can help you can ask.

**Comment by hyr13579** [comment]
Hi Paulo, 
I had the same problem as you, so I installed the perl-5.16.0 version, but it still reported the error:
Unable to read control file
Could you please help me with this problem? thank you very much!
