### ISSUE TITLE
Use env in shebang

### ISSUE THREAD

**Issue by timdiels** [fgvieira/badirate#2]
Could the shebang line be replaced with `#!/usr/bin/env perl` please to support systems such as `module load` which add the right perl to use on the PATH? Thanks in advance.

Edit: though it'd also needs dos2unix to be run on it to remove the BOM which, though correct, confuses the shebang parser on linux. https://stackoverflow.com/a/19065575/1031434

**Comment by timdiels** [comment]
Please also consider switching the encoding to UTF8 as shebangs tend not to work on UTF16 files on linux. Perhaps this is why you recommended calling it as `perl BadiRate.pl` instead of calling it directly?

**Comment by fgvieira** [comment]
I can replace the shebang line, but keep in mind that this is not the original repo...

not sure what you mean by the second part though...

**Comment by timdiels** [comment]
How do you mean not the original repo, is it a fork? Isn't this the official BadiRate repo?

By the second part I mean that shebangs won't work unless the first 2 bytes in the file are `#!`. The file is encoded as UTF8 with a byte order mark (BOM) meaning the file starts with 3 bytes, the UTF8 BOM, not `#!`. On windows you can remove these with Notepad++ by selecting http://i.stack.imgur.com/dvtUb.jpg. On linux it can be removed with `tail --bytes=+4 BadiRate.pl > nobom.pl; mv -f nobom.pl BadiRate.pl`

**Comment by fgvieira** [comment]
This was supposed to be just a "backup" repo of the original website (http://www.ub.edu/softevol/badirate/) but, unfortunately, the original has some broken links now. :/

Just fixed both issues...

**Comment by timdiels** [comment]
Thanks!
