### ISSUE TITLE
small estimated ancestral genome size

### ISSUE THREAD

**Issue by Xiaojun928** [fgvieira/badirate#3]
Hi,

Hope this message find you well. I'm using badirate for ancestral genome construction. However, the estimated ancestral genome is far smaller than expected. 
For example, the target genomes have ~1200 orthologous groups (OG), but their estimated ancestral genome has only ~800 OGs.
Is there any related parameter? Here is the command used in my analysis:
> perl BadiRate.pl -treefile iqtree.tre -sizefile iqtree.txt -anc -bmodel FR -family -rmodel BDI -ep CSP > iqtree.bd

Best,
Xiaoyuan

**Comment by fgvieira** [comment]
Hi @Xiaojun928,

thanks for your interest in `badirate`. However, it might be better if you contact the main developer at:
`plibradosanz _a_t_ gmail (dot) com`

**Comment by Xiaojun928** [comment]
> Hi @Xiaojun928,
> 
> thanks for your interest in `badirate`. However, it might be better if you contact the main developer at:
> `plibradosanz _a_t_ gmail (dot) com`

Thank you for your information.
