### ISSUE TITLE
If the software could run under multi threads model?

### ISSUE THREAD

**Issue by qjoypark** [fgvieira/badirate#4]
Thank you for developing such helpful software. I would like to try this software in my next research. I used to use COUNT software to do this, and it will last a long time.

Could you please tell me if this software can be used under multi threads environment ? And the regular time consume to ~100 bacteria genome estimating?

**Comment by fgvieira** [comment]
Thanks for your interest in `badirate`.
I think it might be better if you ask that to the main developed: `plibradosanz _a_t_ gmail (dot) com`

best,
