### ISSUE TITLE
Error:UNIVERSAL does not export anything at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/TreeFunctionsI.pm line 94.

### ISSUE THREAD

**Issue by hyr13579** [fgvieira/badirate#7]
I am trying to use BadiRate 1.35, but I am having some problems to run it in my machine.

When I run perl BadiRate.pl I get the following error:

UNIVERSAL does not export anything at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl/5.22/base.pm line 97.
	...propagated at /usr/share/perl/5.22/base.pm line 106.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /opt/paulo/softwares/badirate-1.35/lib/Bio/TreeIO.pm line 90.
Compilation failed in require at BadiRate.pl line 71.
BEGIN failed--compilation aborted at BadiRate.pl line 71.
One or more DATA sections were not processed by Inline.

The root of the problem seems to be that my perl version is 5.26.1， I installed the perl-5.16.0 version, but it still reported  error:
Unable to read control file
Could you please help me with this problem? thank you very much!

**Comment by fgvieira** [comment]
Hi, I'd recomend contacting the main developer. Check [contact](https://github.com/fgvieira/badirate#contact) under  main README.

**Comment by hyr13579** [comment]
Thanks, I have contacted the main developer and the issue has been resolved. My command_typed incorrectly, resulting in Unable to read control file.

**Comment by fgvieira** [comment]
Cool! Could you then write here how you fixed it?
Just in case other users bump into the same problem.

thanks,

**Comment by hyr13579** [comment]
Ok. First, I solved the first problem by installing perl-5.16.0 version. Then, when I use the example command, I get an error: unable to read control file. This problem is caused by a command error. When I replace the "-" in the command with the "-" of the Chinese keyboard, BadiRate can run normally. Hope my answer can help others.

**Comment by fgvieira** [comment]
Super! thanks for the explanation. 😄
